name: cluster_analysis
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  collection: ^1.17.2
  equatable: ^2.0.5
  mocktail: ^1.0.1

dev_dependencies:
  test: ^1.24.9
  lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec